### ISSUE TITLE
Make classes final

### ISSUE THREAD

**Issue by soullivaneuh** [nexylan/slack#13]

**Comment by soullivaneuh** [comment]
To be done after #6 in order to use the mock http client.

**Comment by arnaspet** [comment]
What's the point of making class final? I can't mock it now with phpspec atleast.

**Comment by soullivaneuh** [comment]
To avoid BC break possible issues.

Could you please paste an example of what you was doing the test?

We may consider adding Interfaces to solve the issue.

**Comment by arnaspet** [comment]
i was just trying to mock slackClient inside test case like so:

```php
use Maknz\Slack\Client;

class SomeClassSpec
{
    function let(Client $slackClient)
    {
        $this->beConstructedWith($slackClient);
    }
}
```

And this gives error:
```
 could not reflect class Nexy\Slack\Client as it is marked final.
```

**Comment by soullivaneuh** [comment]
Right, could you please elaborate a bit of what you want to do?

If it's for a global slack API integration test, please note this library is using `php-http` and a mock client is provided: https://github.com/php-http/mock-client

Would it be enough for your needed? 

We might accept PR to add interfaces if you really need to mock this library directly.
