### ISSUE TITLE
Change to MIT license confirmation

### ISSUE THREAD

**Issue by soullivaneuh** [nexylan/slack#41]
After the discussion in https://github.com/maknz/slack/issues/95 with @maknz, he would like an approbation of all the contributors to confirm the LICENSE change made on v2.0 of this library.

I already did the change because to me, making a new major is enough, as it was done for swift-mailer. It seems not for many people and I'm OK with that.

However, I need an explicit "YES" from each person who has contributed code. Is everyone okay with this?

Of course, if somebody does not want the change, the LICENSE would go back to the v1 one.

- [x] @maknz
- [x] @Soullivaneuh
- [x] @IonBazan
- [x] @drewbroadley
- [x] @freekmurze
- [x] @geodeveloper
- [x] @iwiznia
- [x] @jwcobb
- [x] @Anahkiasen
- [x] @mvatansever
- [x] @vysinsky
- [x] @qmcree
- [ ] @rajabishek
- [x] @stefanzweifel
- [x] @TomasVotruba
- [x] @tzookb
- [x] @rap2hpoutre

**Comment by rap2hpoutre** [comment]
YES

**Comment by vysinsky** [comment]
YES

**Comment by IonBazan** [comment]
YES

**Comment by qmcree** [comment]
YES

**Comment by mvatansever** [comment]
YES

**Comment by freekmurze** [comment]
Sure, go ahead

**Comment by TomasVotruba** [comment]
Yes

**Comment by iwiznia** [comment]
Yes

**Comment by jwcobb** [comment]
Yes

**Comment by stefanzweifel** [comment]
Yes

**Comment by soullivaneuh** [comment]
Ping @maknz @drewbroadley @geodeveloper @Anahkiasen @rajabishek @tzookb

**Comment by tzookb** [comment]
Of course 💪🏽

**Comment by soullivaneuh** [comment]
Ping @maknz @drewbroadley @geodeveloper @Anahkiasen @rajabishek

Please just answer yes, or no. :+1:

**Comment by drewbroadley** [comment]
YES

**Comment by maknz** [comment]
Yes

**Comment by Gummibeer** [comment]
* @Anahkiasen has only changed the `README.md` with a marginal change - so I would say that his agreement is optional.
https://github.com/maknz/slack/commit/b87556810a4dd3db380d918af6b489c79dd8b417
* @rajabishek  has only removed a unused `use` statement - also no change that rly effects the sourcecode and would be copyrightable.
https://github.com/maknz/slack/commit/9b65369b0f79dea6c9e047b1559503a136a55cd6

Only the commit by @geodeveloper is a big one with a real change in the sourcecode and added features. https://github.com/maknz/slack/commit/4e115c4f4217e45154be7e033807097ae0e110c6
The original PR was: https://github.com/maknz/slack/pull/51

**Comment by soullivaneuh** [comment]
Thanks a lot for the resume @Gummibeer! :+1: 

@geodeveloper does not seem to be very active on GitHub nowadays... If anyone have an another way to contact him, I would be grateful to ask him if he can answer to the licence change asking.

**Comment by Gummibeer** [comment]
https://opensource.guide/legal/#what-if-i-want-to-change-the-license-of-my-project

In all cases you have to keep the current *BSD 2* license just add an end-date. Because of the fact that BSD2 & MIT are compatible (so far I understand it) it could be done without his agreement.
You could also add a hint. into the license file and/or source code that these snippets are licensed under BSD2 until they are changed with active MIT.

Last but not least you can write an email to @geodeveloper
> git show 4e115c4f4217e45154be7e033807097ae0e110c6
```
commit 4e115c4f4217e45154be7e033807097ae0e110c6
Author: George <info@geodeveloper.net>
Date: Tue Jun 14 23:08:08 2016 +0200
```

**Comment by soullivaneuh** [comment]
> In all cases you have to keep the current BSD 2 license just add an end-date

This is what I did by pushing a new major version.

> it could be done without his agreement.

Well, it is not what you and @maknz said in https://github.com/maknz/slack/issues/95. Or I misunderstood your sentence. :-)

**Comment by Gummibeer** [comment]
At the moment you only have one https://github.com/nexylan/slack/blob/master/LICENSE file which only contains *MIT*. It should also contain the old *BSD2* with a date-range `2014 - DD-MM-2018`. Now we get to the point of "who has copyright and who not and what is needed to switch the license".
No one here, I think, is a lawyer - so until you ask one you will only get assumptions, ideas und how others understand it. What I would do:
1) write an email to @geodeveloper and wait 1-2 weeks for an answer.
2) add a notice in the license file that everything is now licensed under MIT except the lines added by @geodeveloper (optional add inline license hints)
3) keep this issue open to allow him to answer with `yes`

What github says in this article is that you *could* not need the agreement if the licenses are compatible. Unfortunately there is no license-compatibility-check tool - so it's again guessing if it is or not.

Another option would be to say everything done after (datetime when you transfered the repo and done the license change) is licensed under MIT and everything else is BSD2 until all contributors agree to change the license. 

You have a lot of options, some more legal/safe than the others but without asking a copyright-lawyer you won't get a "this is the way to go" just guesses.

The part with "the lines are BSD2 until they are changed": also this isn't 100% correct in every case. If you only remove a space it doesn't remove the copyright of the original author. To get around this you do have to do a total rewrite of these lines/logic. But there are also guesses that nothing is copyrightable what's not able to do in another way. And if I take a look into the PR https://github.com/maknz/slack/pull/51 the introduced changes are only copy'n'adjust'n'paste of the lines around. The `protected` variables as data-holder, the `if(isset(...))`, the setter&getter and the attributes in the `toArray()` function are nothing which has new logic. Just the same with other names. So it's a valid question to ask if this is copyrightable code or intellectual property.

**Comment by soullivaneuh** [comment]
> At the moment you only have one file which only contains MIT.

Wrong: https://github.com/nexylan/slack/blob/1.x/LICENSE.md

This is exactly why I made a new major.

My end goal is to provide a tool to maintain the LICENSE files of nexylan package, so the requirement would be deleted.

At least, I may add a link to the old LICENSE on the changelog file.

@maknz Do you agree with @Gummibeer about the license compatibility and the end date?

**Comment by Gummibeer** [comment]
Also this is some kind of law-philosophy - is it enough to have the old file in another branch!? :/ If yes it's impossible to don't cover this point on git because there will everytime be a copy of the file in any place (commit).
So far I understand it it has to stay beside the current license - my guess for this.

**Comment by Anahkiasen** [comment]
Yes

**Comment by georgecoca** [comment]
Yes!

Sorry guys for not confirming earlier, somehow I missed all these messages.

**Comment by soullivaneuh** [comment]
Oh right so we have all the confirmations we need, thanks a lot guys! :+1:
