### ISSUE TITLE
bundle-test, integration with symfony

### ISSUE THREAD

**Issue by ashrakat** [nexylan/slack#44]
How could i test this bundle?

**Comment by ashrakat** [comment]
I've tested already, but for others you need to create slack app first and install it in your workspace, then enable incoming  webhooks and URL generated will be your end point that should be added to your .env file
source: https://api.slack.com/slack-apps

**Comment by soullivaneuh** [comment]
Hi @ashrakat,

You need this bundle for full integration: https://github.com/nexylan/slack-bundle

Regards
