### ISSUE TITLE
Link Action Buttons

### ISSUE THREAD

**Issue by violuke** [nexylan/slack#46]
Hi,

Are "Link Action Buttons" supported? I can't see how to set the URL for them.

https://api.slack.com/docs/message-attachments#link_buttons

Thanks for the great library 😄

**Comment by soullivaneuh** [comment]
Hi @violuke,

AFAIK, it is: https://github.com/nexylan/slack/blob/9fb986882dd635f2eefc5cc06030e8f7fce4caed/src/Attachment.php#L134-L140

You may thanks also @maknz who did the library first. :wink:

**Comment by violuke** [comment]
Thanks for the reply! I'm thinking we need to pass an [AttachmentAction](https://github.com/nexylan/slack/blob/master/src/AttachmentAction.php) into the main message object, but I can't see there how to set the `url`... or is there a way to specify manual attachment jons/array instead of the objects? Thanks

**Comment by soullivaneuh** [comment]
Honestly, I don't know as I don't use this feature.

Feel free to contribute if you want! :+1:

**Comment by balazscsaba2006** [comment]
Hi, I've created a PR to include link buttons, #52
