### ISSUE TITLE
Choice of channel - am I missing something?

### ISSUE THREAD

**Issue by phtmgt** [nexylan/slack#48]
Maybe it's just me, but aren't slack webhooks supposed to work with a single channel only? If yes, how come we've got `$client->to('#accounting')`?

**Comment by soullivaneuh** [comment]
Hi @plamenh,

Slack webhooks have default channels, but you can use it to push message elsewhere.

Is that you what looking for? If not, please explain a bit more your issue.

Regards

**Comment by p11v** [comment]
Yes, I want to push to other channels, but it does not work. I believe slack only allows to publish to the default channel.

**Comment by soullivaneuh** [comment]
@plamenh Could you please provide a code sample so I can reproduce your issue?

**Comment by p11v** [comment]
Sure:

```php
$slack = $this->get('nexy_slack.client');
        $message = $slack->createMessage();
        $message
            ->to('#XXX')
            ->from($payload['username'])
            ->withIcon($payload['icon_emoji'])
            ->setText($payload['username'].' - '.$payload['attachments'][0]['text'])
        ;
        if (isset($payload['attachments'][0]['image_url'])) {
            $message->attach((new Attachment())
                ->setFallback($payload['attachments'][0]['image_url'])
                ->setImageUrl($payload['attachments'][0]['image_url'])
            );
        }

        try {
            $slack->sendMessage($message);
            $data = true;
        } catch (\Exception $e) {
            $data = $e;
        }
```

Regardless of what I set in $message->to('#XXX'), it always posts in the channel that is pre-set in the webhook settings.

**Comment by soullivaneuh** [comment]
Well, I copy pasted your code with my data:

```php
$payload = [
    'username' => 'jhon',
    'icon_emoji' => 'wink',
    'attachments' => [
        [
            'text' => 'test',
            'image_url' => 'https://avatars3.githubusercontent.com/u/14073311?s=88&v=4'
        ]
    ]
];
$message = $slack->createMessage();
$message
    ->to('#test_manual')
    ->from($payload['username'])
    ->withIcon($payload['icon_emoji'])
    ->setText($payload['username'].' - '.$payload['attachments'][0]['text'])
;
if (isset($payload['attachments'][0]['image_url'])) {
    $message->attach((new Attachment())
        ->setFallback($payload['attachments'][0]['image_url'])
        ->setImageUrl($payload['attachments'][0]['image_url'])
    );
}

try {
    $this->sendMessage($message);
    $data = true;
} catch (\Exception $e) {
    $data = $e;
}
```

And it works as expected (the default channel is `#general` for my hook).

My configuration (from symfony) is pretty simple:

```yaml
nexy_slack:
    endpoint: '%slack_endpoint%'
```

So I don't think this is an issue with this library, sorry. :-/

Try to dump the sent request and work on it with curl to debug.

Regards

**Comment by p11v** [comment]
Ok, then maybe it's an issue with us. Thanks for the confirmation that it works, though.

**Comment by p11v** [comment]
I finally found the issue: The functionality you are describing only works with legacy webhooks. The new, app-based webhooks don't allow posting to different channels.

**Comment by ewartx** [comment]
I do actually want the feature of being able to dynamically send to different team members. Does this mean there is no way to achieve the same thing with the new app-based webhooks?

**Comment by soullivaneuh** [comment]
@plamenh @ewartx We currently use the legacy webhooks and didn't plan to update the library yet.

If you want, you are welcome to contribute with a PR. :+1:
