### ISSUE TITLE
Using multiple channels

### ISSUE THREAD

**Issue by JohnnySteunwijzer** [nexylan/slack#61]
How can I use the select channel feature when I have to select only 1 channel when creating a webhook?

**Comment by soullivaneuh** [comment]
Could you please elaborate a bit your question with a concrete case and some code samples?

**Comment by JohnnySteunwijzer** [comment]
I didnt read for enough.

> Incoming webhooks have a default channel, but it can be overridden in your JSON payload. A public channel can be specified with "channel": "#other-channel", and a Direct Message with "channel": "@username"

This answered my question. Package works great!
