### ISSUE TITLE
Allow ClientInterface in Message::__construct() argument

### ISSUE THREAD

**Issue by jaikdean** [nexylan/slack#65]
`Message`'s constructor requires a `Client` instance. Since there is now a `ClientInterface`, could the typehint for this argument be updated to use it?

**Comment by soullivaneuh** [comment]
Of course, would you like to work on it?

Ref: https://github.com/nexylan/slack/blob/7be31f06859f099477a7505a5791628359ac81ae/src/Message.php#L102-L105
