### ISSUE TITLE
Return ResponseInterface in sendMessage method

### ISSUE THREAD

**Issue by zakirullin** [nexylan/slack#67]
I can make a PR myself, would you like to merge it?
Need to get sent message's ID, so I can later start a thread using that ID. That's kind of essential. Wouldn't break back compatibility. That's it to say, I have a better way - not gonna expose raw ResponseInterface outside

**Comment by soullivaneuh** [comment]
Hi,

I'm not sure of what you want to change, but you can make a PR of course. :+1:

**Comment by zakirullin** [comment]
I did, check that out!
